# Generated by Django 5.2.16 on 2026-09-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffprofile_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='designation',
        ),
    ]
