# Generated by Django 5.2.16 on 2026-09-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('RECEPTIONIST', 'Receptionist'), ('GYM_KEEPER', 'Gym Keeper'), ('TRAINER', 'Trainer')], default='RECEPTIONIST', max_length=15),
        ),
    ]
