# Generated by Django 5.2.16 on 2026-09-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_replace_department_with_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
