# Generated by Django 5.2.16 on 2026-10-01 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_softdelete_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'db_table': 'shifts',
                'ordering': ['start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to='staff.shift')),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['STAFF', 'TRAINER']}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Shift',
                'verbose_name_plural': 'Staff Shifts',
                'db_table': 'staff_shifts',
                'ordering': ['weekday', 'shift__start_time', 'staff__last_name'],
                'constraints': [models.UniqueConstraint(fields=('staff', 'shift', 'weekday'), name='unique_staff_shift_per_weekday')],
            },
        ),
    ]
