# Generated by Django 6.0.7 on 2026-07-17 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_number', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, help_text='e.g. "Men\'s Block A", "Women\'s Block B"', max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance'), ('RESERVED', 'Reserved')], db_index=True, default='AVAILABLE', max_length=15)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, help_text='Fee per month for locker rental', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Locker',
                'verbose_name_plural': 'Lockers',
                'db_table': 'lockers',
                'ordering': ['locker_number'],
            },
        ),
        migrations.CreateModel(
            name='LockerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lockers.locker')),
                ('member', models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='locker_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Locker Assignment',
                'verbose_name_plural': 'Locker Assignments',
                'db_table': 'locker_assignments',
                'ordering': ['-start_date'],
            },
        ),
    ]
