# Generated by Django 5.2.16 on 2026-07-26 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee per month for locker rental', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
