# Generated by Django 5.2.16 on 2026-09-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_backfill_branch_access'),
        ('lockers', '0003_locker_branch_locker_gym_lockerassignment_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='locker_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='locker',
            constraint=models.UniqueConstraint(fields=('gym', 'branch', 'locker_number'), name='unique_locker_number_per_branch'),
        ),
    ]
