# Generated by Django 5.2.16 on 2026-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_gymmembership_one_default_gym_per_user'),
        ('lockers', '0004_alter_locker_locker_number_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='locker',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('gym', 'locker_number'), name='unique_locker_number_per_gym_without_branch'),
        ),
        migrations.AddConstraint(
            model_name='locker',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True), ('gym__isnull', True)), fields=('locker_number',), name='unique_legacy_locker_number'),
        ),
    ]
