# Generated by Django 5.2.16 on 2026-09-24 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_backfill_branch_access'),
        ('members', '0002_memberprofile_branch_memberprofile_gym_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='memberprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('gym__isnull', True)), fields=('user',), name='unique_legacy_member_profile_user'),
        ),
    ]
