# Generated by Django 6.0.7 on 2026-07-17 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, help_text='e.g. weight in kg, distance in km, time in seconds', max_digits=8)),
                ('unit', models.CharField(default='kg', help_text='Unit for the value (kg, km, seconds, reps, etc.)', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='workouts.exercise')),
                ('member', models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Record',
                'verbose_name_plural': 'Personal Records',
                'db_table': 'personal_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hips_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bicep_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('thigh_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Entry',
                'verbose_name_plural': 'Progress Entries',
                'db_table': 'progress_entries',
                'ordering': ['-date'],
                'unique_together': {('member', 'date')},
            },
        ),
    ]
