# Generated by Django 5.2.16 on 2026-08-31 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        ('workouts', '0008_workoutcompletionlog_set_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalrecord',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_records', to='workouts.workoutassignment'),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='best_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='best_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='best_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_records', to='workouts.workoutcompletionlog'),
        ),
    ]
