# Generated by Django 5.2.16 on 2026-09-24 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        ('progress', '0002_personalrecord_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalrecord',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='gyms.branch'),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='gyms.branch'),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='gyms.gym'),
        ),
    ]
