# Generated by Django 5.2.16 on 2026-09-24 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_backfill_missing_tenancy'),
        ('progress', '0003_personalrecord_branch_personalrecord_gym_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progressentry',
            unique_together={('gym', 'member', 'date')},
        ),
        migrations.AddConstraint(
            model_name='progressentry',
            constraint=models.UniqueConstraint(condition=models.Q(('gym__isnull', True)), fields=('member', 'date'), name='unique_legacy_progress_member_date'),
        ),
    ]
