# Generated by Django 5.2.16 on 2026-07-29 07:15

from django.db import migrations, models




def backfill_display_ids(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    RoleSequence = apps.get_model('accounts', 'RoleSequence')

    prefixes = {
        'OWNER': 'OWN',
        'STAFF': 'STF',
        'TRAINER': 'TRN',
        'MEMBER': 'MEM',
    }

    for role, prefix in prefixes.items():
        seq, _ = RoleSequence.objects.get_or_create(role=role, defaults={'last_value': 0})
        users = User.objects.filter(role=role).order_by('date_joined', 'id')
        for user in users:
            seq.last_value += 1
            user.display_id = f'{prefix}-{seq.last_value:04d}'
            user.save(update_fields=['display_id'])
        seq.save(update_fields=['last_value'])


def noop_reverse(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'role_sequences',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='display_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(backfill_display_ids, noop_reverse),
    ]
