# Generated by Django 5.2.16 on 2026-09-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_middle_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rolesequence',
            constraint=models.UniqueConstraint(fields=('role',), name='role_seq_unique'),
        ),
    ]
