# Generated by Django 5.2.16 on 2026-09-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Receptionist'), ('TRAINER', 'Trainer'), ('MEMBER', 'Member'), ('ADMIN', 'Admin')], db_index=True, default='MEMBER', max_length=10),
        ),
    ]
