# Generated by Django 5.2.16 on 2026-09-24 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('card', 'Card')], max_length=20)),
                ('reference', models.CharField(db_index=True, max_length=40, unique=True)),
                ('status', models.CharField(default='paid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Subscription',
                'db_table': 'plan_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
