# Generated by Django 5.2.16 on 2026-09-24 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_plansubscription'),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscription',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_subscriptions', to='gyms.gym'),
        ),
    ]
