# Generated by Django 5.2.16 on 2026-08-05 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['OWNER', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plans_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved')], default='DRAFT', max_length=15),
        ),
        migrations.CreateModel(
            name='WorkoutPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plan_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plan_assignments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workouts.workoutplan')),
            ],
            options={
                'verbose_name': 'Workout Plan Assignment',
                'verbose_name_plural': 'Workout Plan Assignments',
                'db_table': 'workout_plan_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('plan', 'member')},
            },
        ),
    ]