# Generated by Django 6.0.7 on 2026-08-09 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_drop_legacy_plan_fields_and_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(help_text='Serialized days + exercises at the time this version was captured.')),
                ('reason', models.CharField(help_text='e.g. "submitted_for_review", "approved", "manual"', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_template_versions_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workouts.workouttemplate')),
            ],
            options={
                'verbose_name': 'Workout Template Version',
                'verbose_name_plural': 'Workout Template Versions',
                'db_table': 'workout_template_versions',
                'ordering': ['-created_at'],
            },
        ),
    ]