# Generated by Django 5.2.16 on 2026-08-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_add_template_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutcompletionlog',
            name='set_logs',
            field=models.JSONField(blank=True, default=list, help_text='Per-set data, e.g. [{"set":1,"weight":80,"reps":10},{"set":2,"weight":80,"reps":8}]'),
        ),
    ]
