# Generated by Django 5.2.16 on 2026-09-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_branch_equipment_gym_and_more'),
        ('gyms', '0003_backfill_branch_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number__isnull', True), _negated=True), fields=('gym', 'serial_number'), name='unique_equipment_serial_per_gym'),
        ),
    ]
