# Generated by Django 5.2.16 on 2026-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipment_serial_number_and_more'),
        ('gyms', '0004_gymmembership_one_default_gym_per_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(condition=models.Q(('gym__isnull', True), ('serial_number__isnull', False)), fields=('serial_number',), name='unique_legacy_equipment_serial'),
        ),
    ]
