# Generated by Django 5.2.16 on 2026-07-30 07:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membership_price_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED_AMOUNT', 'Fixed Amount (NPR)')], default='PERCENTAGE', max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 20 for 20%) or fixed amount in NPR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('applicability', models.CharField(choices=[('ALL_PLANS', 'All Plans'), ('SPECIFIC_PLANS', 'Specific Plans')], default='ALL_PLANS', max_length=15)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum total uses across all members (null = unlimited)', null=True)),
                ('max_uses_per_member', models.PositiveIntegerField(default=1, help_text='Maximum times a single member can use this offer')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plans', models.ManyToManyField(blank=True, help_text='Applicable plans (when applicability is SPECIFIC_PLANS)', related_name='offers', to='memberships.membershipplan')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('EXHAUSTED', 'Exhausted'), ('DISABLED', 'Disabled')], db_index=True, default='ACTIVE', max_length=12)),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Max times this specific code can be redeemed')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_codes_created', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='memberships.offer')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'db_table': 'promo_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text='Promo code used for this membership (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='memberships.promocode'),
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_code_usage', to='memberships.membership')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='memberships.promocode')),
            ],
            options={
                'verbose_name': 'Promo Code Usage',
                'verbose_name_plural': 'Promo Code Usages',
                'db_table': 'promo_code_usages',
                'ordering': ['-used_at'],
            },
        ),
    ]
