# Generated by Django 5.2.16 on 2026-08-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_offer_promocode_membership_promo_code_promocodeusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='promocodeusage',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='promocodeusage',
            name='member',
        ),
        migrations.RemoveField(
            model_name='promocodeusage',
            name='membership',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.DeleteModel(
            name='PromoCodeUsage',
        ),
    ]
