# Generated by Django 5.2.16 on 2026-09-09 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_recreate_offer_promocode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['member', 'status'], name='idx_membership_member_status'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['status', 'end_date'], name='idx_membership_status_enddate'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['renewed_from'], name='idx_membership_renewed_from'),
        ),
    ]
