# Generated by Django 5.2.16 on 2026-09-24 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        ('memberships', '0007_membership_idx_membership_member_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezerequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='gyms.branch'),
        ),
        migrations.AddField(
            model_name='freezerequest',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='membership',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='gyms.branch'),
        ),
        migrations.AddField(
            model_name='membership',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='gyms.branch'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='offer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='gyms.branch'),
        ),
        migrations.AddField(
            model_name='offer',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='gyms.branch'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='gyms.branch'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='gyms.gym'),
        ),
    ]
