# Generated by Django 5.2.16 on 2026-09-24 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_backfill_branch_access'),
        ('memberships', '0008_freezerequest_branch_freezerequest_gym_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.UniqueConstraint(fields=('gym', 'name'), name='unique_membership_plan_name_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('gym', 'name'), name='unique_offer_name_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.UniqueConstraint(fields=('gym', 'code'), name='unique_promo_code_per_gym'),
        ),
    ]
