# Generated by Django 5.2.16 on 2026-09-24 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_backfill_branch_access'),
        ('memberships', '0009_alter_membershipplan_name_alter_offer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.UniqueConstraint(condition=models.Q(('gym__isnull', True)), fields=('name',), name='unique_legacy_membership_plan_name'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('gym__isnull', True)), fields=('name',), name='unique_legacy_offer_name'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.UniqueConstraint(condition=models.Q(('gym__isnull', True)), fields=('code',), name='unique_legacy_promo_code'),
        ),
    ]
