# Generated by Django 5.2.16 on 2026-09-24 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_backfill_branch_access'),
        ('trainers', '0003_trainermemberassignment_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='trainerprofile',
            constraint=models.UniqueConstraint(fields=('gym', 'user'), name='unique_trainer_profile_per_gym'),
        ),
    ]
