# Generated by Django 5.2.16 on 2026-09-24 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_backfill_branch_access'),
        ('trainers', '0004_alter_trainerprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('gym__isnull', True)), fields=('user',), name='unique_legacy_trainer_profile_user'),
        ),
    ]
