# Generated by Django 5.2.16 on 2026-09-07 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_qrattendancetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_type', models.CharField(choices=[('FINGERPRINT', 'Fingerprint'), ('FACE', 'Face Recognition'), ('IRIS', 'Iris Scan'), ('OTHER', 'Other')], default='FINGERPRINT', max_length=15)),
                ('biometric_id', models.CharField(help_text='Device-specific biometric template ID/hash from the scanner hardware', max_length=128)),
                ('device_id', models.CharField(blank=True, db_index=True, help_text='Biometric scanner hardware ID that enrolled this member', max_length=50)),
                ('status', models.CharField(choices=[('NOT_ENROLLED', 'Not Enrolled'), ('ENROLLED', 'Enrolled'), ('FAILED', 'Enrollment Failed'), ('DISABLED', 'Disabled')], default='ENROLLED', max_length=15)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_device', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_enrollments', to=settings.AUTH_USER_MODEL)),
                ('member', models.OneToOneField(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Record',
                'verbose_name_plural': 'Biometric Records',
                'db_table': 'biometric_records',
                'ordering': ['member__first_name', 'member__last_name'],
            },
        ),
    ]
