# Generated by Django 5.2.16 on 2026-09-24 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_branch_attendance_gym_and_more'),
        ('gyms', '0003_backfill_branch_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricrecord',
            name='member',
            field=models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qrattendancetoken',
            name='member',
            field=models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendance_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('gym', 'user', 'date')},
        ),
        migrations.AddConstraint(
            model_name='biometricrecord',
            constraint=models.UniqueConstraint(fields=('gym', 'member'), name='unique_biometric_record_per_gym_member'),
        ),
        migrations.AddConstraint(
            model_name='qrattendancetoken',
            constraint=models.UniqueConstraint(fields=('gym', 'member'), name='unique_qr_token_per_gym_member'),
        ),
    ]
