# Generated by Django 5.2.16 on 2026-09-24 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_biometricrecord_member_and_more'),
        ('gyms', '0003_backfill_branch_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('gym__isnull', True)), fields=('user', 'date'), name='unique_legacy_attendance_user_date'),
        ),
    ]
