# Generated by Django 5.2.16 on 2026-09-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_softdelete_and_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('QR', 'QR Code'), ('BIOMETRIC', 'Biometric'), ('MANUAL', 'Manual')], db_index=True, default='MANUAL', max_length=12),
        ),
    ]
