# Generated by Django 6.0.7 on 2026-07-17 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MEMBERSHIP_EXPIRY', 'Membership Expiry'), ('MEMBERSHIP_RENEWAL', 'Membership Renewal'), ('PAYMENT_DUE', 'Payment Due'), ('PAYMENT_RECEIVED', 'Payment Received'), ('INACTIVITY', 'Inactivity Alert'), ('WORKOUT_REMINDER', 'Workout Reminder'), ('GENERAL', 'General'), ('ANNOUNCEMENT', 'Announcement')], db_index=True, max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_membership_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_payment_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
