# Generated by Django 5.2.16 on 2026-09-06

import re
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _parse_sent_name(title):
    """Best-effort parse of the legacy 'Message from X' / 'Reply from X' titles."""
    if not title:
        return None
    match = re.match(r'^(?:Message|Reply) from (.+)$', title.strip())
    if not match:
        return None
    return match.group(1).strip()


def backfill_notification_sender(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    User = apps.get_model('accounts', 'User')

    def full_name(user):
        """get_full_name() is unavailable on historical models."""
        return f"{user.first_name} {user.last_name}".strip()

    # Only notifications that follow the legacy title convention can be
    # backfilled with confidence. Everything else (system notifications, etc.)
    # keeps sender=null.
    name_to_user = {
        full_name(u): u.pk for u in User.objects.filter(is_active=True).iterator()
    }
    email_to_user = {
        u.email: u.pk for u in User.objects.filter(is_active=True).iterator()
    }

    to_update = []
    for n in Notification.objects.exclude(sender_id__isnull=False).iterator():
        parsed_name = _parse_sent_name(n.title)
        if not parsed_name:
            continue
        matched_id = name_to_user.get(parsed_name) or email_to_user.get(parsed_name)
        if matched_id:
            n.sender_id = matched_id
            to_update.append(n)

    if to_update:
        Notification.objects.bulk_update(to_update, ['sender_id'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_groupmessage_is_edited_notification_is_edited_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sent_notifications',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_notification_sender, noop_reverse),
    ]
