# Generated by Django 5.2.16 on 2026-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MEMBERSHIP_EXPIRY', 'Membership Expiry'), ('MEMBERSHIP_RENEWAL', 'Membership Renewal'), ('PAYMENT_DUE', 'Payment Due'), ('PAYMENT_RECEIVED', 'Payment Received'), ('INACTIVITY', 'Inactivity Alert'), ('WORKOUT_REMINDER', 'Workout Reminder'), ('GENERAL', 'General'), ('ANNOUNCEMENT', 'Announcement'), ('MEMBER_MESSAGE', 'Member Message'), ('TRAINER_REPLY', 'Trainer Reply'), ('TRAINER_ASSIGNED', 'Trainer Assigned')], db_index=True, max_length=25),
        ),
    ]
