# Generated by Django 5.2.16 on 2026-09-24 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        ('notifications', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='gyms.branch'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='gyms.branch'),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='notification',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='gyms.branch'),
        ),
        migrations.AddField(
            model_name='notification',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='pinnedconversation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='gyms.branch'),
        ),
        migrations.AddField(
            model_name='pinnedconversation',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='gyms.gym'),
        ),
    ]
