# Generated by Django 5.2.16 on 2026-09-24 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_backfill_branch_access'),
        ('notifications', '0009_groupmessage_branch_groupmessage_gym_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pinnedconversation',
            name='unique_pinned_conversation',
        ),
        migrations.AddConstraint(
            model_name='pinnedconversation',
            constraint=models.UniqueConstraint(fields=('gym', 'branch', 'user', 'kind', 'target_id'), name='unique_pinned_conversation'),
        ),
    ]
