# Generated by Django 6.0.7 on 2026-07-17 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('goal', models.CharField(blank=True, choices=[('WEIGHT_LOSS', 'Weight Loss'), ('MUSCLE_GAIN', 'Muscle Gain'), ('MAINTENANCE', 'Maintenance'), ('ENDURANCE', 'Endurance')], max_length=15)),
                ('daily_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('carbs_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('fat_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_plans_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diet Plan',
                'verbose_name_plural': 'Diet Plans',
                'db_table': 'diet_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('MORNING_SNACK', 'Morning Snack'), ('LUNCH', 'Lunch'), ('AFTERNOON_SNACK', 'Afternoon Snack'), ('DINNER', 'Dinner'), ('POST_WORKOUT', 'Post Workout'), ('PRE_WORKOUT', 'Pre Workout')], max_length=20)),
                ('time_suggestion', models.TimeField(blank=True, null=True)),
                ('food_items', models.JSONField(default=list, help_text='List of food items, e.g. [{"name": "Oats", "amount": "100g", "calories": 370}]')),
                ('total_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='diet.dietplan')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
                'db_table': 'meals',
                'ordering': ['meal_type'],
            },
        ),
    ]
