# Generated by Django 5.2.16 on 2026-08-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_upgrade_diet_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='carbs_g',
            field=models.PositiveIntegerField(blank=True, help_text='Carbohydrates target in grams', null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='fats_g',
            field=models.PositiveIntegerField(blank=True, help_text='Fats target in grams', null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='protein_g',
            field=models.PositiveIntegerField(blank=True, help_text='Protein target in grams', null=True),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='food_items',
            field=models.JSONField(default=list, help_text='[{"name": "Rice", "amount": "150g", "calories": 200}]'),
        ),
    ]
