# Generated by Django 5.2.16 on 2026-09-29 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_dietplan_branch_dietplan_gym_meallog_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meallog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MealChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_meal_types', models.JSONField(default=list, help_text='Meal type codes checked off that day, e.g. ["BREAKFAST", "LUNCH"]')),
                ('total_meals', models.PositiveIntegerField(default=0, help_text='Snapshot of how many meals were in the effective plan on this date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='meal_checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Checklist',
                'verbose_name_plural': 'Meal Checklists',
                'db_table': 'meal_checklists',
                'ordering': ['-date'],
                'unique_together': {('member', 'date')},
            },
        ),
    ]
